#PBS -A open
#PBS -l nodes=1:ppn=1
#PBS -l pmem=12gb
#PBS -j oe
#PBS -l walltime=12:00:00
#PBS -mae
#PBS -M rbm166@psu.edu
#PBS -N fit_40topic_114
#PBS -o PBSout_ExpAgenda_40topics_114
cd ~/work/cong_text/03-topic_modeling/ExpAgenda/
pwd

module load r/3.4

eval "Rscript 01-estimating_ExpAgenda.R --topics 40 --kappa 100 --delta 0.0001 --infile ./Processed/ExpAgenda_Processed_114.RData --outpath ./Fits/114/ --outfile modelfit_40_114.RData --logpath ./Logs/114/ --logfile modellog_40_114.Rout"
