#PBS -A open
#PBS -l nodes=1:ppn=1
#PBS -l pmem=12gb
#PBS -j oe
#PBS -l walltime=12:00:00
#PBS -mae
#PBS -M rbm166@psu.edu
#PBS -N fit_30topic_113
#PBS -o PBSout_ExpAgenda_30topics_113
cd ~/work/cong_text/03-topic_modeling/ExpAgenda/
pwd

module load r/3.4

eval "Rscript 01-estimating_ExpAgenda.R --topics 30 --kappa 100 --delta 0.0001 --infile ./Processed/ExpAgenda_Processed_113.RData --outpath ./Fits/113/ --outfile modelfit_30_113.RData --logpath ./Logs/113/ --logfile modellog_30_113.Rout"
